@startuml
class Particle {
- List<BigDecimal> position
- List<BigDecimal> velocity
- List<BigDecimal> best
- BigDecimal bestFit
+ void positionInit(Integer,List<BigDecimal>,List<BigDecimal>,FitnessFunction)
+ void velocityInit(Integer)
+ void velocityUpdate(BigDecimal,BigDecimal,BigDecimal,List<BigDecimal>)
+ void positionUpdate(List<BigDecimal>,List<BigDecimal>,FitnessFunction)
}


@enduml