@startuml
class ParticleSwarm {
- Particle gBestParticle
- List<Particle> particles
- Integer nPop
- Integer dim
- List<BigDecimal> positionUp
- List<BigDecimal> positionDown
- BigDecimal wMax
- BigDecimal wMin
- BigDecimal c1
- BigDecimal c2
- Integer maxIt
- FitnessFunction fitnessFunction
+ void initParticles()
+ List<BigDecimal> iterativeParticles()
}


@enduml